### ISSUE TITLE
Toys Guix Channel Search

### ISSUE THREAD

**Issue by jgarte** [jamartin9/guix-channel#1]
Hi fellow Guixer,

Would you be interested in joining our Guix channel search engine?

https://toys.whereis.みんな/

If so, send a patch here adding your channel:

https://git.sr.ht/~whereiseveryone/toys#join

**Comment by jamartin9** [comment]
Hello fellow guixer :wave: 
Cool project and thanks for your consideration in reaching out. :heart:

I will have to think about it tbh... I do not want to break anyone with a bad package, force push, removal of package, change of key, moving the repo location etc. 

This was just a place for my personal usage and I am unsure if I want to support more than that atm (CI/tests/versions/etc).
